#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=3:00:00
#SBATCH -J pygroupfindCDM
#SBATCH -p general
#SBATCH -o log.txt
#SBATCH -e log.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=dncross@iu.edu
#SBATCH --mem=58G

module purge

module load PrgEnv-intel
module load gsl 
module load cray-hdf5
module load cray-fftw
module load pmi-lib
module load openmpi
module load slurm

export OMP_NUM_THREADS=9  
ulimit -s 1024000
srun python run_in_python.py ../evolutions/10Mpc_256_CDM/files/output_snapshot_names.txt 




