#!/bin/bash
#SBATCH -p gpu
#SBATCH --gres=gpu:v100:1
#SBATCH -J omega1p2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=2-0:00:00
#SBATCH -o log
#SBATCH --mail-user=dncross
#SBATCH --mail-type=BEGIN,END
module purge
module load cudatoolkit
export OMP_NUM_THREADS=8


python visualize.py


